### ISSUE TITLE
Add a way to disable certain targets

### ISSUE THREAD

**Issue by ChristophP** [solidjs-community/tsup-preset-solid#1]
Hi, 👋 

thanks for making this preset. It makes writing SolidJS libs a lot easier. Especially with the automatically generated `exports` object, which can get quite complicated.

In terms of complexity, the generated conditions for the entrypoint file look like this.
```json
    "./server": {
      "worker": {
        "solid": "./dist/server/server.jsx",
        "import": {
          "types": "./dist/server/index.d.ts",
          "default": "./dist/server/server.js"
        },
        "require": "./dist/server/server.cjs"
      },
      "browser": {
        "solid": {
          "development": "./dist/server/dev.jsx",
          "import": "./dist/server/index.jsx"
        },
        "development": {
          "import": {
            "types": "./dist/server/index.d.ts",
            "default": "./dist/server/dev.js"
          },
          "require": "./dist/server/dev.cjs"
        },
        "import": {
          "types": "./dist/server/index.d.ts",
          "default": "./dist/server/index.js"
        },
        "require": "./dist/server/index.cjs"
      },
      "deno": {
        "solid": "./dist/server/server.jsx",
        "import": {
          "types": "./dist/server/index.d.ts",
          "default": "./dist/server/server.js"
        },
        "require": "./dist/server/server.cjs"
      },
      "node": {
        "solid": "./dist/server/server.jsx",
        "import": {
          "types": "./dist/server/index.d.ts",
          "default": "./dist/server/server.js"
        },
        "require": "./dist/server/server.cjs"
      },
      "solid": {
        "development": "./dist/server/dev.jsx",
        "import": "./dist/server/index.jsx"
      },
      "development": {
        "import": {
          "types": "./dist/server/index.d.ts",
          "default": "./dist/server/dev.js"
        },
        "require": "./dist/server/dev.cjs"
      },
      "import": {
        "types": "./dist/server/index.d.ts",
        "default": "./dist/server/index.js"
      },
      "require": "./dist/server/index.cjs"
    },
```

This is quite hard to process when reading. There are a lot of conditions for `browser`, `worker`, `deno` etc which all don't apply to our use case because we only use `node`. We could remove them manually to make the `exports` field easier to read, but that has two drawbacks.
1. It won't work with `writePackageJson` since it will get overriden on every build
2. It makes the output of `printInstructions` less copy-pasteable.

So I was thinking it would be great if there was an option to supress the generation of unwanted targets. Is this something that could be considered as an additional feature?

**Comment by thetarnav** [comment]
Hey @ChristophP 
I had my notifications disabled for this repo so I haven't seen this issue until now lol 🙈

The export conditions for separate client/server entries are based on the ones in [solid package.json](https://github.com/solidjs/solid/blob/main/packages/solid/package.json).
This preset is mainly targeted for oss use, where you have to consider all runtimes.

But I'm planning to add an ability to extend the generation of package.json fileds to add/remove some fields as needed.
This could be used to add addtional, non-js entries to the exports that are not covered by the preset.

**Comment by ChristophP** [comment]
Hi @thetarnav That sounds nice.
Adding something for exports for things like stylesheets would definitively be a great addition.
